[package]
name = "bevy_jobs"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
async-channel = "1"
bevy_app = "0.12"
bevy_ecs = "0.12"
bevy_tasks = "0.12"
bevy_log = "0.12"
instant = "0.1"
